package com.munna.www;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

public class CreateStudentTable {
	public static void main(String[] args)throws Exception {

		
		System.out.println("munna");
		Class.forName("oracle.jdbc.driver.OracleDriver");
		Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "admin");

		String createTableSQL = "CREATE TABLE student ("
                + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "name VARCHAR2(100), "
                + "age NUMBER, "
                + "email VARCHAR2(100)"
                + ")";
        PreparedStatement ps = con.prepareStatement(createTableSQL);
        ps.executeUpdate();
        System.out.println("Student table created successfully!");
        
        ps.close();
        con.close();

		
		
	}
}
